version: "3.3"
services:
  antiphotosbot:
    build: .
    image: antiphotosbot
    env_file:
      - .env
    container_name: antiphotosbot-container
    restart: unless-stopped

  antiphotosbot-minio:
    image: minio/minio
    container_name: minio-container
    restart: unless-stopped
    command: server --console-address ":9001" /data
    ports:
      - "9001:9001"
    env_file:
      - .env
    volumes:
      - antiphotosbot-minio-data:/data

volumes:
    antiphotosbot-minio-data:
